# Generated by Django 3.1.7 on 2021-02-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120, unique=True)),
                ('pages', models.IntegerField(default=50)),
                ('price', models.IntegerField(default=50)),
                ('anchor', models.CharField(max_length=75)),
            ],
        ),
    ]
